### ISSUE TITLE
move use cases about identifications to the collections folder?

### ISSUE THREAD

**Issue by kcranston** [DINA-Web/dina-use-cases#15]
I've started going through the taxonomy use cases, and created some [initial notes](https://github.com/DINA-Web/dina-use-cases/blob/master/taxonomy/organization.md). 

If you look at the [Actions](https://github.com/DINA-Web/dina-use-cases/blob/master/taxonomy/organization.md#actions-implied-by-the-use-cases) section of that doc, many of the use cases in `taxonomy` are about identifications. Do others agree that use cases about associating specimens with identifications are primarily _collections_ use cases rather than _taxonomy_ use cases? In other words, where does the identification table reside - the collections module or the taxonomy model?

**Comment by cgendreau** [comment]
+1
