### ISSUE TITLE
Example of two-level identifiers

### ISSUE THREAD

**Issue by mikkohei13** [DINA-Web/dina-use-cases#20]
Could someone give an example of two-level identifiers on the case https://github.com/DINA-Web/dina-use-cases/blob/master/collection/12-Add_a_second_level_catalog_number_to_a_specimen_draft.md
What does the higher and lower-level identifiers refer to?

I don't recall ever seeing two-level identifiers.

**Comment by cgendreau** [comment]
I may be wrong but I think it could also be an alternative path of https://github.com/DINA-Web/dina-use-cases/blob/master/collection/13-Recognizing_an_additional_individual_for_a_specimen_draft.rst or maybe it is already covered by https://github.com/DINA-Web/dina-use-cases/blob/master/collection/06-Registering_a_specimen_that_belongs_to_a_nested_preparation.rst ?

**Comment by ssbilkhu** [comment]
Here is a herbarium image I found on google: https://www.kew.org/sites/default/files/herbarium%20sheet%20and%20cabinet.jpg 

In the image you can see there is the pressed plant which takes up the majority of the sheet but in the top right corner there is a envelope which may contain more parts of the same specimen or a completely different specimen.  

In this case the plant on the sheet maybe AAFC 1001 - A, where AAFC is the collection, 1001 is the higher level identifier and "A" is the lower level identifier.   The other material in the envelope would be AAFC 1001 - B.

**Comment by mikkohei13** [comment]
Ok, thanks for the example.

The collections I've seen having this kind of specimens haven't had lower-level identifiers: just either no specific identifiers for subunits, or completely unique identifiers for them. I would prefer this approach, as lower-level identifiers would not be persistent (or would carry misleading information) in the case subunit would be detached and made an independent specimen.

Closing this issue.

**Comment by cgendreau** [comment]
I'm still not sure what's the main difference with [06-Registering a specimen that_belongs to a nested preparation](https://github.com/DINA-Web/dina-use-cases/blob/master/collection/06-Registering_a_specimen_that_belongs_to_a_nested_preparation.rst). I would probably update it to add the possibility of having second level identifier (catalog number) in `Alternative paths` and remove `12-Add a second level catalog number to a specimen`.

**Comment by cgendreau** [comment]
Just for clarification, I checked with @ssbilkhu and the lower-level identifier represents the link to the physical piece (e.g. written on the envelope), it still gets a generated unique identifier assigned.
